# Generated by Django 3.2 on 2021-04-13 18:59

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pass_user',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='phone'),
        ),
    ]
